### ISSUE TITLE
Plugin compatibility with Rider RD-222.*

### ISSUE THREAD

**Issue by crow131** [seclerp/rider-efcore#102]
#### Describe the bug

Thanks for the plugin, its great. Rider is just out so this may be in the works already

Steps to reproduce the behaviour:
Is it possible to make the plugin compatible with RD-222.* please?

![image](https://user-images.githubusercontent.com/898917/182527493-745b4160-5fc1-440d-a8af-facb92a459aa.png)

**Comment by seclerp** [comment]
Hey @crow131, in Releases section of the repo you could see 222.0.0 version of plugin that was released yesterday. It takes 1-2 business days to validate it on Marketplace. If you want to install it right now you could do it from .zip file that you can find in the release artifacts list.
