### ISSUE TITLE
Abstract classes can be used as DbContext

### ISSUE THREAD

**Issue by alexb5dh** [seclerp/rider-efcore#106]
#### Describe the bug

Abstract classes can be used in DbContext dropdown. Trying to add migration with one selected fails.

**To Reproduce**

- Define an abstract class inheriting  `DbContext`
- Try to add migration selecting it as "DbContext class"
- See error "No DbContext named '...' was found."

#### Expected behavior

Abstract classes can not be selected.

#### Screenshots

![image](https://user-images.githubusercontent.com/4650832/184497004-e41e1c9a-f20c-405e-b7e8-b30e0cc9f0ed.png)
![image](https://user-images.githubusercontent.com/4650832/184496984-061b10a6-28d5-43bf-b615-1405b1d1371b.png)

#### Environment (please complete the following information):

- OS: Windows 10
- .NET SDK info (installed ones and version used within Rider): 6.0.301
- Plugin version: 222.1.0
- Rider version: 2022.2

#### Additional context

Popup also seems to forget last selected DbContext while remembering all other options. Probably related to https://github.com/seclerp/rider-efcore/issues/54.

**Comment by vova-lantsov-dev** [comment]
In progress, track it here https://github.com/seclerp/rider-efcore/pull/109
