### ISSUE TITLE
Update Database - Connection

### ISSUE THREAD

**Issue by drjohnsonjr** [seclerp/rider-efcore#107]
#### Describe the bug

When using the Update Database feature, it's not possible to specify a non-default connection

**To Reproduce**

1. In Rider, select Tools : Entity Framework Core : Update Database
2. Uncheck "Use default connection of startup project"
3. Enter a connection string without surrounding quotes, or a connection name without surrounding quotes
4. Click preview and note how the connection string is specified in the command with escaped quotes around the connection string.
```
dotnet ef database update --project my.csproj --startup-project my.csproj --context myContext --configuration Debug myBranch --connection \"connectionName\"
```
5. Click OK and see error message.

#### Expected behavior

The connection string in the command should be included in the command with unescaped quotes, and the update should execute.

### Environment (please complete the following information):

- OS: Windows 10
- .NET SDK info (installed ones and version used within Rider): 6.0
- Plugin version: 222.1.0
- Rider version: 2022.2.1

**Comment by seclerp** [comment]
Thanks for the report, seems like double escaping is accidentally applied somewhere in the code. For a temporary workaround, you could try to use "Additional arguments" field if it work for you.

**Comment by drjohnsonjr** [comment]
"Additional arguments" doesn't seem to work as expected.  I will add another bug report so you can see what i mean.

**Comment by seclerp** [comment]
They work as they should - you just need to play with your setup a bit. See https://github.com/seclerp/rider-efcore/issues/108#issuecomment-1215648213

**Comment by vova-lantsov-dev** [comment]
In progress, you can track it here https://github.com/seclerp/rider-efcore/pull/110

**Comment by drjohnsonjr** [comment]
Thank you, Vova, for your very fast responses yesterday!
