### ISSUE TITLE
[Feature Improvement]: Support auto fill in arguments in dialog

### ISSUE THREAD

**Issue by dengyakui** [seclerp/rider-efcore#111]
This plugin is awesome. There are tons of tickets to let JetBrains to provide this feature. 
Respect to You!

But there is a little problems in my  common use.

When I use the plugin to add some migration & update to my local db, the dialog's input control  need to manually input every time the dialog pop up. 
Like  `--environment=<my custom env name>`  is some args I will commonly used.
In my common works, I will use  Development/ Test  envionment to do multi Migraitons & Updates. 
So I need input multi times.
Can we improve this UX.  so developers don't need to input custom args every time.

#### Screenshots
![image](https://user-images.githubusercontent.com/3945919/185018899-aacc4bc7-c957-40c7-8865-00db6b7eff70.png)

**Comment by seclerp** [comment]
Hi @dengyakui, thanks for that! We already have an issue to track such feature request: https://github.com/seclerp/rider-efcore/issues/54

**Comment by dengyakui** [comment]
> Hi @dengyakui, thanks for that! We already have an issue to track such feature request: #54

Thanks @seclerp . I will close this issue.
