### ISSUE TITLE
Select Startup Project shows none

### ISSUE THREAD

**Issue by jmarbutt** [seclerp/rider-efcore#112]
#### Describe the bug

When trying to scaffold a db context it asks for the `Startup Project` which does not exist in the new templates.

**To Reproduce**

1. Create new Console App or ASP.net Core app
2. Go to Tools -> Entity Framework Core -> Scaffold DbContext
<img width="459" alt="image" src="https://user-images.githubusercontent.com/1386587/186027355-69c2a543-e885-4d19-bcc6-16bcd650e0fb.png">

There will be no startup project in the new projects.

#### Expected behavior

Should let you select a startup project

### Environment (please complete the following information):

- OS: MacOS 
- .NET SDK info (installed ones and version used within Rider): 6.0.1
- Rider version: 2022.2

**Comment by seclerp** [comment]
"Startup project" refers to `--startup-project` value passed to the `dotnet ef` command line tool, not `Startup` class.

In this field you should select a project that contains reference to `Microsoft.EntityFrameworkCore.Design` (or `.Tools`).

I assume that in your case it's an ASP.NET Core app project that you are building.

Please read EF Core tools documentations for more details.
