### ISSUE TITLE
Support for Rider 2022.3 EAP 

### ISSUE THREAD

**Issue by ZlobnyiSerg** [seclerp/rider-efcore#127]
Rider EAP is out there with great hot reload (and lot more improvements).
Your plugin requires version 222.*, new Riders has 223.* so plugin is considered to be incompatible. I'm not sure if there are any incompatibilities in plugin API, may be it will be enough to change version requirement?

**Comment by seclerp** [comment]
Hi @ZlobnyiSerg 

Please check [the side note for EAP](https://github.com/seclerp/rider-efcore#using-marketplace) in the README.
