### ISSUE TITLE
Enhancements - Remember last migrations folder & use migration list

### ISSUE THREAD

**Issue by espindl** [seclerp/rider-efcore#129]
1. While adding new migration, migrations folder is being selected. It would be nice if it remembers the last selection. 

2. While updating the database, target migration input might be an option box. INstead of writing the exact name of the migration user may select from a list.

**Comment by seclerp** [comment]
Hi, regarding the first point - it's a well-known feature request and we are working on it :)
Regarding the second one - I was thinking about it and it's a good point. Will create a task for that, thanks!

**Comment by seclerp** [comment]
Please track the issues below according to your request:
1. #54
2. #130
