### ISSUE TITLE
Migrations: Represent `Target migration` field as a dropdown instead of textfield with autocomplete

### ISSUE THREAD

**Issue by seclerp** [seclerp/rider-efcore#130]
Target migration always has a limited and predefined set of available options to choose from. Typing migration name manually is not so comfortable compared to just selecting the migration from the dropdown.

**Comment by marchy** [comment]
Awesome stuff, was just wishing for this the other day.

Was also surprised by the fact that it selected oldest rather than newest migration, which I see you've pushed out in this release as well  🙌
