### ISSUE TITLE
First migrations showing preselected when "Updating Database"

### ISSUE THREAD

**Issue by madman2021** [seclerp/rider-efcore#136]
#### Describe the bug

When pressing Update database the preselected migraitons is the first ever migrations.
**To Reproduce**

1. Add Migration
2. Add second Migrations
3. Press update database
4. Migration created in step 1 is preselected

#### Expected behavior

In the previous version when pressing update database the latest added migration is show as preselected.

#### Screenshots
![image](https://user-images.githubusercontent.com/2904531/207831657-fa84fb3f-75ab-4d83-b178-1320667044b4.png)
![image](https://user-images.githubusercontent.com/2904531/207831707-722e7ed7-a907-4b52-a11a-2ecc4d61e2fa.png)

### Environment (please complete the following information):

- OS: _Windows 11_
- .NET SDK info (installed ones and version used within Rider): __
```
dotnet --list-sdks
3.1.414
5.0.402 - Current project
6.0.402
7.0.100 
- Plugin version: _223.1.0_
- Rider version: _2022.3_

**Comment by Saidnazar08** [comment]
I almost deleted all data from my production database because of this bug.

**Comment by seclerp** [comment]
Hi folks, sorry to hear about the consequences of this newly introduced bug :(

I will try to publish a bug fix as soon as possible to address that.

**Comment by seclerp** [comment]
Please expect a new version in 1-2 working days. I will publish a release today on the Releases page, but marketplace validation could take time.

**Comment by madman2021** [comment]
Thanks pal
