### ISSUE TITLE
When migrations are in the startup project, it's not possible to select DbContext from other project

### ISSUE THREAD

**Issue by Procee** [seclerp/rider-efcore#137]
#### Describe the bug

It's currently not possible to select a DbContext when the migrations and startup projects are the same and the DbContext is contained in a different project.

**To Reproduce**

Create a startup project that uses EF Core. Create another project that houses the DbContexts see: [this example repo](https://github.com/Procee/EfCoreUiMigrations)

I would like to have my migrations in the startup project, but the database context does not show up.

#### Expected behavior

I expect the tool to allow me to select the database context even when it's not directly in the startup project.

#### Screenshots

![image](https://user-images.githubusercontent.com/3168081/209347875-0de3c885-011d-4fc8-9e71-00400afad434.png)

### Environment (please complete the following information):

- OS: Windows
- .NET SDK info (installed ones and version used within Rider):7.0.1
- Plugin version: 2022.3.1
- Rider version: 223.2.0

**Comment by seclerp** [comment]
Hi, thanks for the repro! Are you able to run EF Core commands with such a setup using `dotnet ef`? Could you provide and example?

**Comment by seclerp** [comment]
Ah, I see. You mean that it's impossible to select DbContext that is transitively available in a Migrations project, gotcha

**Comment by Procee** [comment]
Thanks for picking this up, if you have any questions let me know!
