### ISSUE TITLE
DbContext is not persisted

### ISSUE THREAD

**Issue by szingg** [seclerp/rider-efcore#139]
We have multiple DbConexts in our project

When we add a migration, the preselected DbContext is never used for migrations. We need to change the DbContext for every new migration.

It would be great if the DbContext would be persisted. A new migration should preselect the DbContext of the last migration.

**Comment by seclerp** [comment]
Hi, currently DbContext should be already persisted. The last selected value for given Migrations project should be preselected.

Maybe you have this option disabled in settings under `Tools | EF Core UI` section?

![image](https://user-images.githubusercontent.com/20597871/212351440-9963b0ac-ad7e-421b-9646-bc4f0bc0b3b9.png)


Also, see [this file](https://github.com/seclerp/rider-efcore/blob/release/223/docs/values-saved-between-dialogs.md#common) for the list of all persisted values.
> DbContext value: Yes (per Migrations project)

**Comment by szingg** [comment]
My settings look as follows:
![image](https://user-images.githubusercontent.com/11045324/212622170-26dbde6c-5737-4c19-a1ff-bf093980c2b5.png)

Unfortunately, the `DbContext` field is not persisted
