### ISSUE TITLE
Quick access

### ISSUE THREAD

**Issue by xorty-v** [seclerp/rider-efcore#140]
It is inconvenient to go this way every time you need to use the plugin: Click on the solution => Tools => Entity Framework Core => ...
The only solution speeding up this process was to put EF code Quick Action on hotkeys, but for some reason,  there is nothing in the window that opens.
![photo_2023-01-21_19-07-23](https://user-images.githubusercontent.com/40475699/213873156-e80864da-06ff-4649-8ae1-2d6b7ae535e1.jpg)

**Comment by seclerp** [comment]
Hi, thanks for the report! The issue is known and the fix will be available in the next patch release.
