### ISSUE TITLE
action "add migration" is missing in Rider 2023.1. EAP 2

### ISSUE THREAD

**Issue by ursmeili** [seclerp/rider-efcore#142]
I installed the EF Core plugin to Rider 2023.1 EAP 2. It is working properly, however, the usual EF Core actions like "Add Migrations" are missing (at it was always present in earlier versions). I have to go to the context menu in the solution explorer to add a migration instead, which of course is much slower.
![grafik](https://user-images.githubusercontent.com/23562434/216650008-81cbe8f4-1217-4d3a-adb8-2aacd6389524.png)

**Comment by seclerp** [comment]
Hi @ursmeili, thanks, I will think about addressing such a use case.

Currently, I suggest you bind a shortcut to the action called `Entity Framework Core Quick Actions`:
![image](https://user-images.githubusercontent.com/20597871/216651429-8b14e358-3314-41a3-b38b-e443cc108b69.png)

It will allow you to open a popup (similar to what VCS opens) with available actions:
![image](https://user-images.githubusercontent.com/20597871/216651781-e252d3f9-6ddb-4af7-b537-464bc5371715.png)

Additionally, this popup could be opened without a shortcut, as you do it currently:
![image](https://user-images.githubusercontent.com/20597871/216652274-fee85be0-7ffb-4bc3-b8fb-da6a0ca12070.png)

**Comment by ursmeili** [comment]
As mentioned, the action "add migration" was already there until rider
2022.3. It would be nice if it could be restored for the 2023.1 EAP builds.

Andrii Rublov ***@***.***> schrieb am Fr., 3. Feb. 2023,
17:14:
