### ISSUE TITLE
error "Selected migrations project doesn't have migrations" after changing project Name

### ISSUE THREAD

**Issue by NimaQu** [seclerp/rider-efcore#144]
#### Describe the bug

I decided to do some refactoring of my project, I changed my project name in visual studio and added a new project, changed some namespace and folder names, when I switched back to rider I found that I couldn't use Updata Database and Remove Last Migration menu anymore. Manual execution on the command line functions normally.

**To Reproduce**

1. change the project name from `faka` to `FAKA.Server` in visual stuido (I also changed the namespace and folder name I don't know if that impacted)

:warning: **It is highly recommended** to provide a minimal solution that reproduces your issue.

#### Expected behavior
it works normally.

#### Screenshots

![image](https://user-images.githubusercontent.com/26685881/218881970-173ce7bd-6715-4f9f-ab8d-b6ffb04d4d0d.png)
![image](https://user-images.githubusercontent.com/26685881/218883622-80fcce0a-1a14-4fcd-aa27-855bcdcb959d.png)
![image](https://user-images.githubusercontent.com/26685881/218882065-d8e8f2ab-bc13-4226-b2f5-2bb951039e44.png)

### Environment (please complete the following information):

- OS: Windows 11
- .NET SDK info (installed ones and version used within Rider): 7.0
- Plugin version: 223.3.1
- Rider version: 2022.3.2

**Comment by seclerp** [comment]
Hi @NimaQu, am I right that problem occurs when both VS and Rider are opened with the same solution on the same time? And restart fixes the issue?

**Comment by NimaQu** [comment]
> Hi @NimaQu, am I right that problem occurs when both VS and Rider are opened with the same solution on the same time? And restart fixes the issue?

No, I think it's caused by changing the project name and restarting won't fix it

**Comment by seclerp** [comment]
Do you have a repro project?

**Comment by NimaQu** [comment]
> Do you have a repro project? And exact instructions

It looks like I found the reason, I changed the name of the folder from `faka` to `FAKA.Server`. The folder name contain a dot `.` .When I removed that dot `.` from the folder name it worked.

my project: https://github.com/NimaQu/FAKA.Server

**Comment by seclerp** [comment]
Could you please advice me which folder exactly you are trying to rename? I don't see `faka` folder, only `faka.sln` solution file

**Comment by seclerp** [comment]
Maybe you mean changing the solutoon name?
