### ISSUE TITLE
Scaffold: Provider input autocomplete

### ISSUE THREAD

**Issue by Anatholy** [seclerp/rider-efcore#150]
The "**Provider**" field is just a text input.
It would be great if this will be an autocomplete field.
The options may be taken from "**Migration project**" **csproj** file
where the value of "**Include**" attribute of "**PackageReference**"
contains "**sql**"

**Comment by seclerp** [comment]
Thanks for the suggestion, I think it's worth implementing.

Moreover, the better approach to detect such providers is to check NuGets that have `Microsoft.EntityFrameworkCore.Relational` (possibly, transitive) dependency. I will look into it.
