### ISSUE TITLE
Tools greyed out since Rider update

### ISSUE THREAD

**Issue by jerome-poenisch** [seclerp/rider-efcore#151]
#### Describe the bug

Seemingly since one of the latest Rider versions (currently using JetBrains Rider 2022.3.3) the tools are always greyed out for me even in projects where I happily used them previously.

**To Reproduce**

1. Open a project using EntityFrameWork ore
2. Open context menu
3. Go to `Tools`
4. Go to `Entity framework Core ->`
5. **observe**: Greyed out

See https://imgur.com/d8epWDw

#### Expected behavior

The tools should not be greyed out but usable.

### Environment (please complete the following information):

- OS: 
   ```
   Windows 10 Pro
   Version	22H2
   Installed on	‎12/‎10/‎2021
   OS build	19045.2788
   Experience	Windows Feature Experience Pack 120.2212.4190.0
   ```

- .NET SDK info (installed ones and version used within Rider): .NET SDK 7.0
- Plugin version: 223.3.2
- Rider version: 

   ```
   JetBrains Rider 2022.3.3
   Build #RD-223.8836.53, built on March 20, 2023
   Licensed to Unity Technologies ApS
   
   Runtime version: 17.0.6+1-b653.34 amd64
   VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
   Windows 10 10.0
   .NET 7.0.0 (Server GC)
   GC: G1 Young Generation, G1 Old Generation
   Memory: 1500M
   Cores: 16
   Registry:
       ide.new.project.model.index.case.sensitivity=true
       vcs.empty.toolwindow.show=false
       ide.workspace.model.rbs.as.tree=false
       rdclient.asyncActions=false
       platform.projectModel.workspace.model.file.index=false
       database.show.search.tab=false
       indexing.enable.entity.provider.based.indexing=false
   
   Non-Bundled Plugins:
       com.intellij.resharper.HeapAllocationsViewer (2022.3.1)
       me.seclerp.rider.plugins.efcore (223.3.2)
       com.intellij.resharper.StructuredLogging (2022.3.2.289)
       org.vepanimas.uml.javascript (0.2.0)
       PythonCore (223.8836.26)
       com.kagof.pokeprogress (2.1.1)
       cn.yiiguxing.plugin.translate (3.4.2)
   ```

#### Additional context

Installed (EntityFramework) ckages

See https://imgur.com/UOw1J4j

**Comment by seclerp** [comment]
Hi @jerome-poenisch, thanks for the report.

Could you create a minimal repro for that issue? In the 223.3.2 patch release we introduced a fix for that stuff and it should work, so repro will be really helpful.

**Comment by jerome-poenisch** [comment]
[WebApplication1.zip](https://github.com/seclerp/rider-efcore/files/11099442/WebApplication1.zip)

This is a minimal new project where I would expect this to be working.
Am I missing something? Still hoping I'm just holding it wrong 😉

**Comment by seclerp** [comment]
It's really strange, working fine on my side on both old UI and new UI

![image](https://user-images.githubusercontent.com/20597871/228521659-1a3db957-26ca-40fd-b7f8-e62be8af4779.png)

**Comment by jerome-poenisch** [comment]
ha yes @seclerp it works on the project context menu!

Not sure if this changed but I was kind of used to directly do it via the context menu of the migrations folder within the project - that was where I tried i all the time.

Thanks for clarifying this in such a detailed manner!
