### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TeguSolutions** [seclerp/rider-efcore#31]
I am looking for a solution to use EF with Rider (2021.3)

I have .Net 6 projects, with a Server + Data libraries, nugets updated accordingly.

Neither of Add Migration / Update works.

The following error pops up:

Command: dotnet ef database update --project D:\Visual Studio Projects\Tegu\Tegu Solutions\TeguSolutions.Data\TeguSolutions.Data.csproj --startup-project D:\Visual Studio Projects\Tegu\Tegu Solutions\TeguSolutions\Server\TeguSolutions.Server.csproj --context TeguSolutions.Data.Context.TeguDbContext --configuration Debug --framework net6.0 20211209000444_UsersystemroleMtmRelationCreated Output: MSBUILD : error MSB1009: Project file does not exist. Switch: D:\Visual Unable to retrieve project metadata. Ensure it's an MSBuild-based .NET Core project. If you're using custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option. Exit code: 1

![image](https://user-images.githubusercontent.com/20848629/145316730-3793a47b-366e-46fb-99da-b6c66d4ed379.png)

With Visual Studio everything is fine, just for reference.
It is a bug or can I do anything on my side to make it work?

**Comment by seclerp** [comment]
@TeguSolutions thanks for the issue report, seems like the problem is in whitespaces in the project file path.

For temporal workaround try to use folder names without whitespaces. We will fix it in the next bugfix release

**Comment by seclerp** [comment]
@TeguSolutions patch release including a fix for your problem has been released, in 1-2 days it will be available through Marketplace

**Comment by TeguSolutions** [comment]
@seclerp nice, thank you, eagerly waiting.
