### ISSUE TITLE
Empty Migration

### ISSUE THREAD

**Issue by hhakangull** [seclerp/rider-efcore#35]
I tried your plugins, then migration is created, but that's files are empty 
what's problem your plugin ?

![image](https://user-images.githubusercontent.com/34252239/146691877-779442c9-cb84-495d-8ac4-caf2ca228550.png)

**Comment by seclerp** [comment]
Hi @hhakangull, seems like it wasn't 🙂

The plugin relates on `dotnet ef` tool, so if your new migration doesn't differ from previous one, it will be empty
