### ISSUE TITLE
Duplicate Values in Dropdowns

### ISSUE THREAD

**Issue by khalidabuhakmeh** [seclerp/rider-efcore#36]
When looking at the build configuration drop-down, the results are pulling all build configurations from each project in the solution. Also noticing the other fields are duplicating values as well.

<img width="486" alt="Screenshot 2022-01-12 at 08 52 49" src="https://user-images.githubusercontent.com/228256/149153147-5c16c8e0-befb-442b-a19a-a02452d62d0e.png">

<img width="441" alt="Screenshot 2022-01-12 at 08 55 34" src="https://user-images.githubusercontent.com/228256/149153610-1b6b836e-d40d-418b-b9b3-eb5d9439fdbe.png">

I added an additional `<TargetFrameworks>net6.0;net5.0</TargetFrameworks>` which triggered the `DbContext` duplication.

## Expected Behavior

Don't see duplication in the drop-downs. 

See sample project here. https://github.com/MassTransit/Sample-ForkJoint

## Side Note

This is a really cool plug-in and it's pretty amazing. Great job.

**Comment by seclerp** [comment]
Hey @khalidabuhakmeh, thanks for a great catch! Seems like multiple target frameworks and platforms were a blind zone.

I added the fix and it will be available in the next patch release of a plugin.

And also thanks for your appreciation!

**Comment by khalidabuhakmeh** [comment]
Thank you. We ran into a similar issue while writing our plug-in. https://github.com/maartenba/DotNetWatch/
