### ISSUE TITLE
Migrations folder value is not persistent

### ISSUE THREAD

**Issue by VyacheslavPritykin** [seclerp/rider-efcore#53]
"Migrations folder" option in the "Add migration" dialog is not persistent across runs.

**Comment by seclerp** [comment]
Hi @VyacheslavPritykin, currently only "Migrations project" and "Startup project" are persisted. There is a suggestion for extending the list of persisted data (#46)

In the future release, we are planning to improve the persistence of different data across dialogs. For now, it's expected behavior.

**Comment by seclerp** [comment]
I just created an ready to implement issue #54 for that, you could track it if you want.
