### ISSUE TITLE
General: Implement a friendly codebase for persisting dialog selected values

### ISSUE THREAD

**Issue by seclerp** [seclerp/rider-efcore#54]
Currently only "Migrations project" and "Startup project" are persisted.

We have a lot of dialogs with a lot of selectable data on them. When the same dialog is used 

### Progress
- [x] Introduce `DialogsStateService` to load/save dialogs' properties
- [x] Introduce a data binding approach instead of naive UI fields updates
- [x] Adjust the "Add Migration" dialog to use data-binding
- [x] Adjust the "Remove Last Migration" dialog to use data-binding
- [x] Adjust the "Update Database" dialog to use data-binding
- [x] Adjust the "Drop Database" dialog to use data-binding
- [x] Adjust the "Scaffold DbContext" dialog to use data-binding
- [x] Adjust the "Generate SQL Script" dialog to use data-binding
- [x] Create a documentation page for further development of loading/saving data of specific dialogs

**Comment by t3mp0ralflux** [comment]
I've possibly come up with a solution for at least the Scaffold DbContext dialog if you'd be interested in it.  It doesn't cover the Build Options tick at the bottom as that's inherited from the DialogWrapper, but the rest of the fields are holding values.

**Comment by seclerp** [comment]
@t3mp0ralflux thanks! You could create a PR with your suggestion if you want. BTW do we really need to persist data from Scaffold Database runs? I'm not sure that it will be executed often.

**Comment by t3mp0ralflux** [comment]
So with the way I and others I work with use the plugin, we have one base project at work and each ticket usually requires a re-scaffold based on the ticket requirements.  It's nice to not have to re-enter all the info every time I have to do this process, hence the persistence.  I'll put a PR up once I can prove to myself that I didn't break anything along the way.

**Comment by kingmotley** [comment]
We actually do "database first" and every database change is actually done in the database, then scaffolded, and then we create a migration off the new scaffolding.  In our case, it is run very often.  We have a powershell script that automates it, but I'm sure it would be nice for others that do the same.
