### ISSUE TITLE
Correct Startup project has been filtered out

### ISSUE THREAD

**Issue by lxalln** [seclerp/rider-efcore#57]
We have several projects, 2 are relevant:
Domain.csproj
Web.csproj

Domain contains the migrations, and the DbContext class.
Web contains the startup code.

To add a migration is (from within the domain project):
`dotnet ef --startup-project ../web migrations add …`

However the 'Add Migration' dialog does not present the `Web` project as an option.

Startup project list:
<img src="https://user-images.githubusercontent.com/2781908/152138106-b88c5215-3bf3-4e1f-9a39-a2c53767fc32.png" width="400" />

Migrations project list:
<img src="https://user-images.githubusercontent.com/2781908/152138341-52d7e055-58be-47d6-877f-4da8e16ff414.png" width="400" />

**Comment by seclerp** [comment]
Hi @lxalln, which target framework is used in Startup project's project file?

**Comment by lxalln** [comment]
@seclerp net6.0

**Comment by seclerp** [comment]
Does it have one of the following NuGets installed?
- Microsoft.EntityFrameworkCore.Tools
- Microsoft.EntityFrameworkCore.Design

**Comment by lxalln** [comment]
No, neither of those are installed.

`Microsoft.EntityFrameworkCore.Tools` isn't installed in any project.
`Microsoft.EntityFrameworkCore.Design` is installed in the `Domain` project, that contains the migrations.

**Comment by seclerp** [comment]
That's why only Domain is visible in the Startup project drop-down. Are you able to create migrations using Domain as a startup project?

**Comment by lxalln** [comment]
No: "Unable to create an object of type AppDbContext".

From memory, this is why we need to use the Web project for Startup.

**Comment by seclerp** [comment]
Unfortunately, it's not possible to use a project without `.Tools` or `.Design` packages installed as a startup project in plugin dialogs.

This requirement is described in the [article](https://blog.jetbrains.com/dotnet/2022/01/31/entity-framework-core-inside-rider-ui-way/#preparing-the-project):

> For supported projects to appear in dialog boxes, one of the following NuGet packages must be installed in the startup project:
> 
> - `Microsoft.EntityFrameworkCore.Tools`
> - `Microsoft.EntityFrameworkCore.Design`

What you could do for now is to install one of these packages into the `Web` project.

Seems like you have `Microsoft.EntityFrameworkCore.Design` installed as a regular NuGet without PrivateAssets and IncludeAssets declared, this project layout is not supported yet

**Comment by seclerp** [comment]
@lxalln did it work for you?

**Comment by lxalln** [comment]
@seclerp yes, adding the .Design nuget package worked fine.

**Comment by seclerp** [comment]
Closing this for now, please track #58 for detection logic improvements
