### ISSUE TITLE
Migrations: Add SQL script generation for given migrations range

### ISSUE THREAD

**Issue by spaasis** [seclerp/rider-efcore#62]
Hi, and thanks for the great plugin!

I was thinking that it would be a useful feature to add some GUI magic on top of the `ef migrations script` command https://docs.microsoft.com/en-us/ef/core/cli/dotnet#dotnet-ef-migrations-script 
e.g. `dotnet ef migrations script initial -o migration.sql`

Here's how I think it could look like:
1. Two columns listing the migrations in a DbContext
2. Select one from each
3. Click "generate script" or some such description
4. The generated sql is displayed, with an option to save to a file or copy to clipboard

This of course gets a bit more difficult if there are multiple DbContexts to choose from.

**Comment by seclerp** [comment]
Hey @spaasis, thanks for this, will look into and investigate the best UI/UX way of representing it inside dialog

**Comment by ruslanfedoseenko** [comment]
Also will be nice to have checkbox or combox for this arg
-i|--idempotent                        Generate a script that can be used on a database at any migration.
