### ISSUE TITLE
Unable to specify startup profile or environment variable

### ISSUE THREAD

**Issue by sshquack** [seclerp/rider-efcore#63]
Hi @seclerp Thank you so much for creating this awesome plugin ❤️ 

For a project, I have two profiles with difference ASPNETCORE_ENVIRONMENT variable. In the Startup.cs here is the logic I use:
- if it is `Development`, I use the `options.UseInMemoryDatabase`
- if it is `Local` profile then I register the `options.UseSqlServer`

<img width="948" alt="Screenshot 000075@2x" src="https://user-images.githubusercontent.com/5678459/153742192-857eea97-6f2a-4221-9b13-e161b2947fa6.png">

This leads to the plugin always choosing the first profile and it causes failure in migrations.

Is there a way to specify the startup profile or a env var?

**Comment by seclerp** [comment]
Hey @sshquack, unfortunately, it's not possible at that moment

**Comment by seclerp** [comment]
You could now follow issue #65 which will allow doing what you want through command line arguments, but no ETA for now.
