### ISSUE TITLE
Plugin not working on MacOS Rider 2022.1 EAP 3

### ISSUE THREAD

**Issue by irfansagir** [seclerp/rider-efcore#66]
Hi,

When I try to install the plugin I get an error from the rider.

Plugin 'Entity Framework Core UI' (version '1.2.1') is not compatible with the current version of the IDE, because it requires build 213.* or older but the current build is RD-221.4501.83

JetBrains Rider 2022.1 EAP 3
Build #RD-221.4501.83, built on February 16, 2022
Runtime version: 11.0.14+9-b1993.2 aarch64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.

.NET 6.0.1

**Comment by seclerp** [comment]
Hi @irfansagir, sorry for the late response. Currently, the plugin is not published to any 2022.1 EAP version. The next version (1.3.0) that will be available in nearest future will also include support for the latest 2022.1 EAP.

**Comment by irfansagir** [comment]
Hi @seclerp, I apologize for writing at such a bad time. I hope you and your family are well. I hope this war ends soon. My prayers are with you.

**Comment by seclerp** [comment]
Hey @irfansagir, thank you for your support, I really appreciate it! :ukraine:

**Comment by seclerp** [comment]
Hey @irfansagir, we just released `1.3.0` with support for EAP 7. You could now try to install it from marketplace, but make sure to add `eap` channel to your plugins repositories (see README)
