### ISSUE TITLE
Plugin update crashes in Rider 2021.3.3

### ISSUE THREAD

**Issue by ogjtech** [seclerp/rider-efcore#68]
Today I got a pop-up saying there was an update available for Entity Framework Core UI. After install however, an error dialogue of Rider appeared saying the plugin failed to install.

![image](https://user-images.githubusercontent.com/43957930/160856013-af68293f-381f-42cc-85ea-8648a3c0b5c7.png)

After clicking OK, the update is reverted and Rider launches normally.

### Steps to reproduce

1. Launch Rider
2. Open any solution
3. Navigate to Help > Check for Updates...
4. If "Entity Framework Core UI" appears, click "Update"
5. Restart to activate changes

**Comment by seclerp** [comment]
Hi @ogjtech, just tried provided steps - I can't reproduce it.

As I remember there was a random problem with plugin installation when using "Restart" button after plugin upgrade before hitting the "Save" button. Try to
1. Uninstall the plugin
1. Restart Rider
1. Install the plugin
1. Hit Save
1. Click restart on the dialog AFTER hitting Save, not the Restart IDE button near the plugin card

If it will not help you, please provide:
- Exception details
- Your development environment

In the next version, I'm planning to disable the required restarting of IDE after plugin installation as it's not necessary at all.

**Comment by ogjtech** [comment]
Hello @seclerp, thank you for the swift reply!

I could not try your provided possible solution.
This morning I updated Rider to v 2021.3.4 through the Toolbox, which seems to also have installed plugin updates.
Help > Check for Updates... returns "All plugins are up to date" and no errors are shown.

Whatever caused the initial error, it was magically fixed with the IDE update.

Thank you once again for the swift reply!
