### ISSUE TITLE
Startup project is not selectable in an ASP.NET 6 application

### ISSUE THREAD

**Issue by undrivendev** [seclerp/rider-efcore#70]
Hi,
first of all, thanks for the project.

I'm trying to integrate the plugin into my workflow, but when I try to use it in one of my projects, it doesn't work. More specifically, when using the simplified ASP.NET 6 startup model, it seems that the startup project is not selectable in the 'Add Migration' dialog.

You can try it by yourself by downloading the project I'm trying to use it into: [link](https://github.com/undrivendev/template-webapi-aspnet). When I click on the 'Startup project' dropdown after selecting the `WebApiTemplate.Infrastructure` as the 'Migrations project', nothing appears.

I'm on Rider 2021.3.4 on Linux.

![image](https://user-images.githubusercontent.com/17796053/161446544-00462110-df7f-417c-8186-4c07ac4797f9.png)

**Comment by seclerp** [comment]
Hi @undrivendev, thanks for the issue.

See https://github.com/seclerp/rider-efcore/issues/57#issuecomment-1028121735

**Comment by undrivendev** [comment]
Ahh, thank you, I missed it. It worked like a charm, thank you! :)
Closing.

All the best, take care.

Luca
