### ISSUE TITLE
Plugin is not compatible with the latest Rider 2022.1 version

### ISSUE THREAD

**Issue by sbyzova** [seclerp/rider-efcore#72]
The current plugin version is not compatible with the latest Rider 2022.1.
Could you please fix this?

**Comment by seclerp** [comment]
Hey @sbyzova, yesterday we made required changes to make it work in 2022.1.

That version (1.3.1) is still under review on JB side, will be available in the next day or two

**Comment by seclerp** [comment]
@sbyzova a few minutes ago it was approved and now available for download.

In the future in the case when you need it immediately, you could install a new version using a zip file from Releases section
