### ISSUE TITLE
Option to configure path of dotnet

### ISSUE THREAD

**Issue by raaffaaeell** [seclerp/rider-efcore#75]
Currently I have to work with multiple versions of dotnet (3.1, 5, 6) on Linux and the easiest way to manage (that I now) is to have all the versions not included in my paths and create aliases to each dotnet exec (I have dotnet3, dotnet5, dotnet6)

Would be nice if this tool could pickup the one selected by the project or allow me to select the executable path

Cheers, nice extension

**Comment by seclerp** [comment]
Yes, this is a reasonable request and it will be implemented in terms of #96, so it will reuse the same `dotnet` CLI used by a solution. Including the ability to change it to anything else.

But ETA at that time :)
