### ISSUE TITLE
EF Core command failed in Linux

### ISSUE THREAD

**Issue by cmcglownjr** [seclerp/rider-efcore#86]
#### Describe the bug

When I try to run any of the Entity Framework Core UI tools I get the same error. "EF Core command failed". The error shows the command that I tried however if I were to copy the command into the terminal in Rider the command will execute.

**To Reproduce**

1. Create a new ASP.NET Core Web Application. SDK: Net 6, Web App (MVC), Individual Authentication
2. Try to use the tool

#### Expected behavior

This is the error I received:
`Command: dotnet ef database update --project /home/<username>/<path-to-project>/<projectname>.csproj --startup-project /home/<username>/<path-to-project>/<projectname>.csproj --context <projectname>.Data.ApplicationDbContext --configuration Debug 00000000000000_CreateIdentitySchema Output: Unable to retrieve project metadata. Ensure it's an SDK-style project. If you're using a custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option. Error: Could not execute because the application was not found or a compatible .NET SDK is not installed. Possible reasons for this include: * You intended to execute a .NET program: The application 'msbuild' does not exist. * You intended to execute a .NET SDK command: It was not possible to find any installed .NET SDKs. Install a .NET SDK from: https://aka.ms/dotnet-download Exit code: 1`

### Environment (please complete the following information):

- OS: Ubuntu 20.04.4 x86_64
- .NET SDK info (installed ones and version used within Rider): (installed) 3.1, 5; (using) Net 6.0.301
- Plugin version: 1.4.0
- Rider version: 2022.1.2

#### Additional context

I have manually installed the .Net SDKs that I used because snap is annoying. I don't know if that affects this bug.

**Comment by seclerp** [comment]
Hi
Which terminal do you use for manual command execution? Is it the same as the default one in Ubuntu? Seems like the default one's (which is used by `GeneralCommandLine` we are using from Intellij SDK) environment is used when executing commands via the plugin.

**Comment by cmcglownjr** [comment]
The terminal I use is the default in Rider's environment so /bin/bash.

**Comment by seclerp** [comment]
Are you able to execute command manually from any location, not only from the solution folder?

**Comment by cmcglownjr** [comment]
No I execute the command in the project folder or the solution folder using the terminal window in Rider. If I were to run the command from, for example, my home directory then I would get that error. I think the command from the EF Core tool is not being run from the solution or project directory.

**Comment by seclerp** [comment]
That's the reason. In the current implementation, we are running commands not from solution directory, but using absolute paths to startup and migrations projects.

I'm working on huge refactoring right now that contains necessary change (to also support the local `dotnet ef` tool) so in the next major update, the issue should be fixed. But it will be available starting from **2022.2** version of Rider.

**Comment by cmcglownjr** [comment]
Ok thank you for your hard work on this tool.

**Comment by seclerp** [comment]
Closing this as a fix will be available in the next update.
