### ISSUE TITLE
My "Startup project" dropdown is empyt

### ISSUE THREAD

**Issue by jazzn3rd** [seclerp/rider-efcore#97]
#### Describe the bug

I cannot select any project as "startup project" in the dialog.
The migrations project combobox lists all projects.

#### Expected behavior

I would like to choose the startupproject that iIuse when I debugging my solution

#### Screenshots

![image](https://user-images.githubusercontent.com/52830735/180610825-2f00dfd4-7d65-403f-be37-605aba940ff4.png)
![image](https://user-images.githubusercontent.com/52830735/180610828-62883e4f-f495-4785-b1f2-4314aa840bc4.png)

### Environment (please complete the following information):

- OS: _ Windows 11
- .NET SDK info (installed ones and version used within Rider): .NET
- Plugin version: _1.4
- Rider version: 2022.1

**Comment by seclerp** [comment]
Hi @jazzn3rd 

Please look at https://github.com/seclerp/rider-efcore/issues/76#issuecomment-1111205292 and make sure that your startup project **meets the requirements**. 

If you are still not able to fix your issue - please share `.csproj` file of your expected startup project.

**Comment by jazzn3rd** [comment]
Thank you for a superquick response. 
I was missing out on the nuget-package. Solved after adding Microsoft.EntityFrameworkCore.Design
